server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user-management
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: restaurant-management
          uri: http://localhost:8083
          predicates:
            - Path=/restaurants/**, 
        - id: order-management
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, 
        - id: delivery-management
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, 
        - id: payment-management
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://userManagement:8080
          predicates:
            - Path=, 
        - id: restaurant-management
          uri: http://restaurantManagement:8080
          predicates:
            - Path=/restaurants/**, 
        - id: order-management
          uri: http://orderManagement:8080
          predicates:
            - Path=/orders/**, 
        - id: delivery-management
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/deliveries/**, 
        - id: payment-management
          uri: http://paymentManagement:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
